import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Provider from "@/context/Provider";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import { PrismaClient } from "@prisma/client";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Bang Store",
  description: "Generated by create next app",
};
const prisma = new PrismaClient();
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <ToastContainer
              position="top-right"
              autoClose={1000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
            <header className="sticky top-0 shadow-md p-3 backdrop-blur-md bg-white/50 z-50">
              <nav className="flex items-center justify-between gap-3">
                <Link href={"/"} className="px-3 py-1 rounded-lg shadow-md">
                  Home
                </Link>
                <Link
                  href={"/login"}
                  className="px-3 py-1 rounded-lg shadow-md"
                >
                  Login
                </Link>
              </nav>
            </header>
            {children}
          </Provider>
        </body>
      </html>
    );
  }
  const user = await prisma.user.findUnique({
    where: {
      email: session?.user?.email as string,
    },
    select: {
      id: true,
      image: true,
      email: true,
      currentOrder: {
        select: {
          products: true,
        },
      },
    },
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          <Navbar user={user} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
